apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web ## mesmo selector do deployment, ou seja, o selector indica quais pods o service deve direcionar o tráfego
  ports:
    - port: 3000
      targetPort: 3000